// import Head from "next/head";
// import Image from "next/image";
// import { Inter } from "next/font/google";
// import styles from "@/styles/Home.module.css";

//
import Hero from "@/components/home-page/Hero";
import FeaturedPosts from "@/components/home-page/FeaturedPosts";

// const inter = Inter({ subsets: ["latin"] });

const FEATURED_POSTS = [
  {
    postSlug: "getting-started-nextjs-1",
    title: "Getting started with NextJS",
    image: "getting-started-nextjs-1.png",
    excerpt:
      "The React Framework for the Web. Used by some of the world's largest companies, Next.js enables you to create full-stack Web applications by extending the latest React features, and integrating powerful Rust-based JavaScript tooling for the fastest builds.",
    date: "2023-12-15",
  },
  {
    postSlug: "getting-started-nextjs-2",
    title: "Getting started with NextJS",
    image: "getting-started-nextjs-2.png",
    excerpt:
      "The React Framework for the Web. Used by some of the world's largest companies, Next.js enables you to create full-stack Web applications by extending the latest React features, and integrating powerful Rust-based JavaScript tooling for the fastest builds.",
    date: "2023-12-15",
  },
  {
    postSlug: "getting-started-nextjs-3",
    title: "Getting started with NextJS",
    image: "getting-started-nextjs-3.png",
    excerpt:
      "The React Framework for the Web. Used by some of the world's largest companies, Next.js enables you to create full-stack Web applications by extending the latest React features, and integrating powerful Rust-based JavaScript tooling for the fastest builds.",
    date: "2023-12-15",
  },
];

export default function Home() {
  return (
    <>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      {/* <main className={`${styles.main} ${inter.className}`}></main> */}
      <Hero />
      <FeaturedPosts posts={FEATURED_POSTS} />
    </>
  );
}
